In [1]:
##Lecture 15 
###numpy 

#stands for numerical python 

#extrememly fast data generationand handling 
#utilises arrays better than a list 

###the most commonly used libraries 
###after this we will learn about pandas 

##numpy arrays 
##numpy indexing and selection 
##numpy operations 
#numpy exercise and solution 

In [2]:
#Lecture 16 
##numpy arrays
import numpy as np 

In [3]:
#creating a numpy array 
my_list = [1,2,3]
x = np.array(my_list)

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
####for financial data you wouldnt normally go above 2d data

In [8]:
list(range(0,5)) ###there is a numpy version of this called arrange 

[0, 1, 2, 3, 4]

In [10]:
###this is the numpy version of it 
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(1,11,2) #the end digit is the step size

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(3)##for 1d array

array([ 0.,  0.,  0.])

In [15]:
#for 2d array 

np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
np.zeros((5,5,5)) #is this a 3d array?

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [17]:
####there is a ones function that is similar to zeros

np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [18]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [19]:
np.ones((4,4,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [33]:
############another thing you might use is linspace
np.linspace(0, 10,30) ##spaces numbers equally between a start and a end 

array([  0.        ,   0.34482759,   0.68965517,   1.03448276,
         1.37931034,   1.72413793,   2.06896552,   2.4137931 ,
         2.75862069,   3.10344828,   3.44827586,   3.79310345,
         4.13793103,   4.48275862,   4.82758621,   5.17241379,
         5.51724138,   5.86206897,   6.20689655,   6.55172414,
         6.89655172,   7.24137931,   7.5862069 ,   7.93103448,
         8.27586207,   8.62068966,   8.96551724,   9.31034483,
         9.65517241,  10.        ])

In [23]:
####identity matrix 
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [24]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [25]:
######using numpys rendom option 
np.random.rand(1) #this is a random number between zero and one

array([ 0.30580977])

In [26]:
np.random.rand(5,4) #creates a matrix of the size specified of numbers between zero and one 


             

array([[ 0.90939041,  0.62133052,  0.26536442,  0.96205099],
       [ 0.94959253,  0.12188216,  0.03803006,  0.36050586],
       [ 0.77033915,  0.18373914,  0.19893583,  0.82464316],
       [ 0.76466846,  0.06708548,  0.62559131,  0.15734899],
       [ 0.34327747,  0.55615117,  0.37045297,  0.21993538]])

In [30]:
np.random.randn(5)  #this is a standard normal distribution 

array([ 0.23803695, -1.19887249, -1.36437467,  0.01709662,  0.28928273])

In [32]:
np.random.randn(5,5) #this is creating an array of standard normally distributed numbers

array([[-0.44249144,  0.21009037,  1.06664368,  1.20875869,  0.44147487],
       [ 0.01657099,  0.90789557,  0.67894794,  1.20981807,  0.52194696],
       [ 0.76694066, -1.15852823,  0.60640876, -1.67892645, -0.40329676],
       [-1.05281784,  0.05498439, -1.12905103,  0.42319236,  0.91325155],
       [-0.10808457,  0.05542489, -0.68627229,  0.08316047, -0.0592619 ]])

In [35]:
np.random.randint(1,500)

118

In [36]:
np.random.randint(1,500,10) ##10 number random integers

array([203, 382, 172, 261, 369,  90,  79, 427, 262, 267])

In [41]:
arr = np.arange(25) ###an array that is a list of numbers  between 0 and not including 25
ranarr = np.random.randint(0,50,10) #10 random numbers between 0 and not including 50
                        

In [40]:
ranarr

array([ 8, 25, 48, 22, 47, 39, 22, 25, 24, 15])

In [ ]:
#####continue at 12 mins 
